# name: Build and push test-images
# on:
#   push:
#     branches:
#       - 'dockerfile-test'
#     paths:
#       - "*"
#       - "!README.md"
#       - "!build.rb"
# jobs:
#   build:
#     runs-on: ubuntu-latest
#     strategy:
#       matrix:
#         include:
#           - base: davma/jupyter-tensorflow-pyodbc:3.10
#             tag: '3.10'
#           - base: davma/jupyter-tensorflow-pyodbc:3.9
#             tag: '3.9'
#           - base: davma/jupyter-tensorflow-pyodbc:3.8
#             tag: '3.8'
#           - base: davma/jupyter-tensorflow-pyodbc:latest
#             tag: latest

#     steps:
#       -
#         name: Checkout 
#         uses: actions/checkout@v2
#       -
#         name: Login to Docker Hub
#         uses: docker/login-action@v1
#         with:
#           username: ${{ secrets.DOCKER_HUB_USERNAME }}
#           password: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}
#       -
#         name: Set up Docker Buildx
#         uses: docker/setup-buildx-action@v1
#       -
#         name: Build and push
#         uses: docker/build-push-action@v2
#         with:
#           context: .
#           file: ./Dockerfile
#           push: true
#           tags: ${{ secrets.DOCKER_HUB_USERNAME }}/test-jupyter-ansible-tf:${{ matrix.tag }}
#           build-args: |
#             IMAGE=${{ matrix.base }}
